# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1.1.1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Restore Ubuntu cache
      uses: actions/cache@v1
      if: matrix.operating-system == 'ubuntu-latest'
      with:
        path: ~/.cache/pip
        key: ${{ matrix.os }}-${{ matrix.python-version }}-${{ hashFiles('**/setup.py')}}
        restore-keys: ${{ matrix.os }}-${{ matrix.python-version }}-
    - name: Install dependencies
      run: |
        sudo python -m pip install --upgrade pip
        sudo apt-get install libturbojpeg
        sudo pip install Cython
        sudo pip install -r requirements.txt
        sudo pip install pycocotools
    - name: Run black
      run:
        black --check .
    - name: Run flake8
      run: flake8
    - name: Run Mypy
      run: mypy iglovikov_helper_functions
    - name: tests
      run: pytest
